/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WikiRouteImport } from './routes/wiki'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RawRouteImport } from './routes/raw'
import { Route as IngestRouteImport } from './routes/ingest'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WikiSlugRouteImport } from './routes/wiki.$slug'

const WikiRoute = WikiRouteImport.update({
  id: '/wiki',
  path: '/wiki',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RawRoute = RawRouteImport.update({
  id: '/raw',
  path: '/raw',
  getParentRoute: () => rootRouteImport,
} as any)
const IngestRoute = IngestRouteImport.update({
  id: '/ingest',
  path: '/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiSlugRoute = WikiSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => WikiRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ingest': typeof IngestRoute
  '/raw': typeof RawRoute
  '/settings': typeof SettingsRoute
  '/status': typeof StatusRoute
  '/wiki': typeof WikiRouteWithChildren
  '/wiki/$slug': typeof WikiSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ingest': typeof IngestRoute
  '/raw': typeof RawRoute
  '/settings': typeof SettingsRoute
  '/status': typeof StatusRoute
  '/wiki': typeof WikiRouteWithChildren
  '/wiki/$slug': typeof WikiSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ingest': typeof IngestRoute
  '/raw': typeof RawRoute
  '/settings': typeof SettingsRoute
  '/status': typeof StatusRoute
  '/wiki': typeof WikiRouteWithChildren
  '/wiki/$slug': typeof WikiSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ingest'
    | '/raw'
    | '/settings'
    | '/status'
    | '/wiki'
    | '/wiki/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ingest'
    | '/raw'
    | '/settings'
    | '/status'
    | '/wiki'
    | '/wiki/$slug'
  id:
    | '__root__'
    | '/'
    | '/ingest'
    | '/raw'
    | '/settings'
    | '/status'
    | '/wiki'
    | '/wiki/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IngestRoute: typeof IngestRoute
  RawRoute: typeof RawRoute
  SettingsRoute: typeof SettingsRoute
  StatusRoute: typeof StatusRoute
  WikiRoute: typeof WikiRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wiki': {
      id: '/wiki'
      path: '/wiki'
      fullPath: '/wiki'
      preLoaderRoute: typeof WikiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raw': {
      id: '/raw'
      path: '/raw'
      fullPath: '/raw'
      preLoaderRoute: typeof RawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingest': {
      id: '/ingest'
      path: '/ingest'
      fullPath: '/ingest'
      preLoaderRoute: typeof IngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/$slug': {
      id: '/wiki/$slug'
      path: '/$slug'
      fullPath: '/wiki/$slug'
      preLoaderRoute: typeof WikiSlugRouteImport
      parentRoute: typeof WikiRoute
    }
  }
}

interface WikiRouteChildren {
  WikiSlugRoute: typeof WikiSlugRoute
}

const WikiRouteChildren: WikiRouteChildren = {
  WikiSlugRoute: WikiSlugRoute,
}

const WikiRouteWithChildren = WikiRoute._addFileChildren(WikiRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IngestRoute: IngestRoute,
  RawRoute: RawRoute,
  SettingsRoute: SettingsRoute,
  StatusRoute: StatusRoute,
  WikiRoute: WikiRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
